const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const page=await browser.newPage({baseURL:'http://127.0.0.1:8552',viewport:{width:1480,height:1050},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const output=path.resolve(__dirname,'../reports/ui');await fs.mkdir(output,{recursive:true});
 const loaded=async()=>{await page.waitForFunction(()=>document.querySelector('#loading').hidden&&!document.querySelector('#export').disabled);};
 await page.goto('http://127.0.0.1:8552/');await loaded();
 assert(await page.locator('#credits-table tbody tr').count()>25);
 await page.screenshot({path:path.join(output,'01-missions.png'),fullPage:true});
 await page.getByRole('button',{name:'Écologie, développement et mobilité durables ›',exact:true}).click();await loaded();
 assert((await page.locator('#scope-title').textContent()).includes('Écologie'));
 const nominal=await page.locator('#summary').innerText();
 await page.locator('#constant').check();await loaded();
 assert((await page.locator('#currency-label').textContent()).includes('Euros 2025'));
 const baseResponse=await page.request.get('/api/explorer?'+new URL(page.url()).searchParams.toString());const base=await baseResponse.json();
 const point=base.totals.find(y=>y.year===2023).PLF;
 assert(Math.abs(point.value-point.nominal*100/97.12)<0.02);
 await page.screenshot({path:path.join(output,'02-ecologie.png'),fullPage:true});
 await page.locator('[data-mode="series"]').click();
 assert((await page.locator('#credits-table thead').innerText()).includes('Évolution'));
 assert.equal(await page.locator('#credits-table tbody tr.total td').count(),7);
 await page.screenshot({path:path.join(output,'05-statistiques.png'),fullPage:true});
 await page.locator('[data-mode="compare"]').click();
 await page.locator('#credits-table .amount').first().click();await page.locator('#source-dialog .source-card').first().waitFor();
 assert((await page.locator('#source-content').innerText()).includes('SHA-256'));
 await page.locator('#close-source').click();
 const exclude=page.locator('#credits-table .exclude').first();await exclude.click();await loaded();
 assert.equal(await page.locator('#exclude-count').innerText(),'1');
 await page.locator('#save').click();await page.reload();await loaded();assert.equal(await page.locator('#exclude-count').innerText(),'1');
 await page.locator('[data-restore]').first().click();await loaded();
 await page.locator('[data-view="movements"]').click();assert((await page.locator('#movements-table').innerText()).includes('Reports'));
 await page.locator('[data-view="documents"]').click();await page.locator('.document').first().waitFor();
 await page.locator('#doc-search').fill('ecologie');await page.waitForFunction(()=>document.querySelectorAll('.document').length>0&&document.querySelectorAll('.document').length<15);
 const href=await page.locator('.document a.open').first().getAttribute('href');const pdf=await page.request.get(href);assert.equal(pdf.status(),200);assert.equal((await pdf.body()).subarray(0,5).toString(),'%PDF-');
 await page.screenshot({path:path.join(output,'03-documents.png'),fullPage:true});
 await page.locator('[data-view="coverage"]').click();assert((await page.locator('#coverage').innerText()).includes('2026'));
 const csv=await page.request.get('/api/export?start=2023&end=2025&scope=EA&measure=CP&budget=BG');assert.equal(csv.status(),200);assert((await csv.text()).includes('Montant EUR'));
 assert.equal((await page.request.get('/api/source/../../etc/passwd')).status(),404);
 await page.setViewportSize({width:390,height:844});await page.locator('[data-view="credits"]').click();await page.screenshot({path:path.join(output,'04-mobile.png'),fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false);
 assert.deepEqual(errors,[]);
 await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,errors,documentsPDFTested:href,checks:['missions','drill','inflation','provenance','exclusion','saved','movements','documents','PDF','coverage','annual-statistics','CSV','path','mobile']},null,2));
 await browser.close();console.log('Browser checks passed.');
})().catch(e=>{console.error(e);process.exit(1);});
