const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try {
  const page=await browser.newPage({baseURL:'http://127.0.0.1:8552',viewport:{width:1480,height:1050}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const output=path.resolve(__dirname,'../reports/ui-maprimerenov');await fs.mkdir(output,{recursive:true});
  const loaded=()=>page.waitForFunction(()=>document.querySelector('#loading').hidden&&!document.querySelector('#export').disabled);
  const current=async()=>{const r=await page.request.get('/api/explorer?'+new URL(page.url()).searchParams);assert.equal(r.status(),200);return r.json();};
  await page.goto('/');await loaded();
  assert(await page.locator('#topic-panel').isHidden());
  await page.locator('#topic').selectOption('maprimerenov');await loaded();
  assert(await page.locator('#topic-panel').isVisible());
  assert.equal((await current()).totals.find(y=>y.year===2025).EXEC.value,null);
  await page.locator('[data-topic-example="series"]').click();await loaded();
  let data=await current();
  assert.equal(data.rows.length,3);
  assert.deepEqual(data.totals.map(y=>y.EXEC.value),[1259900000,2101700000,1887372951,1072217721]);
  assert.equal(data.totals.reduce((s,y)=>s+y.EXEC.value,0),6321190672);
  assert((await page.locator('#summary').innerText()).includes('4 exercices additionnés'));
  await page.locator('#topic-panel summary').click();
  assert((await page.locator('.topic-timeline').innerText()).includes('P362'));
  assert((await page.locator('.topic-timeline').innerText()).includes('P135'));
  await page.screenshot({path:path.join(output,'01-dossier.png'),fullPage:true});
  const button=page.locator('#credits-table .amount[data-stage="EXEC"][data-year="2024"][data-cell-scope=""]');
  await button.click();await page.locator('#source-dialog .source-card').first().waitFor();
  assert((await page.locator('#source-content').innerText()).includes('Part MaPrimeRénov’'));
  const pdfHref=await page.locator('#source-content a[href$="#page=48"]').first().getAttribute('href');
  const pdf=await page.request.get(pdfHref);assert.equal(pdf.status(),200);assert.equal((await pdf.body()).subarray(0,5).toString(),'%PDF-');
  await page.locator('#close-source').click();
  await page.locator('#constant').check();await loaded();data=await current();
  assert(Math.abs(data.totals.at(-1).EXEC.value-1072217721*100/99.07)<0.011);
  await page.locator('#save').click();await page.reload();await loaded();
  assert.equal(await page.locator('#topic').inputValue(),'maprimerenov');
  assert(await page.locator('#constant').isChecked());
  await page.locator('#reset').click();await loaded();
  assert(await page.locator('#topic-panel').isHidden());
  await page.locator('[data-saved="0"]').click();await loaded();
  assert.equal(await page.locator('#topic').inputValue(),'maprimerenov');
  assert(await page.locator('#constant').isChecked());
  await page.locator('#constant').uncheck();await loaded();
  await page.locator('[data-topic-example="ecology"]').click();await loaded();data=await current();
  const normal=await (await page.request.get('/api/explorer?start=2024&end=2024&scope=TA&measure=CP')).json();
  const parent=normal.totals[0].EXEC;
  assert.equal(data.totals[0].EXEC.nominal_cents,parent.nominal_cents-69201772100);
  assert.equal(data.totals[0].EXEC.status,'ok');
  const plain174=normal.rows.find(r=>r.code==='174').series[0].EXEC;
  assert.equal(data.rows.find(r=>r.code==='174').series[0].EXEC.nominal_cents,plain174.nominal_cents-69201772100);
  const same203=data.rows.find(r=>r.code==='203').series[0].EXEC;
  assert.equal(same203.value,normal.rows.find(r=>r.code==='203').series[0].EXEC.value);
  await page.screenshot({path:path.join(output,'02-ecologie-hors-dispositif.png'),fullPage:true});
  await page.locator('#credits-table .amount[data-stage="EXEC"][data-cell-scope="TA"]').click();
  await page.locator('#source-dialog .source-card').first().waitFor();
  assert((await page.locator('#source-content').innerText()).includes('À retirer : MaPrimeRénov’'));
  await page.locator('#close-source').click();
  const request='/api/export?'+new URL(page.url()).searchParams;
  const csv=await page.request.get(request);assert.equal(csv.status(),200);
  const content=await csv.text();assert(content.includes('Montant retiré EUR courants'));assert(content.includes('692017721,0'));assert(content.includes('#page=446'));assert(content.includes('Retirer le dispositif identifié'));
  const downloadEvent=page.waitForEvent('download');await page.locator('#export').click();const downloaded=await downloadEvent;
  await downloaded.saveAs(path.join(output,'ecologie-hors-maprimerenov.csv'));
  await page.locator('[data-view="movements"]').click();assert((await page.locator('#movements-table').innerText()).includes('ouverts'));
  const fine=await (await page.request.get('/api/explorer?topic=maprimerenov&scope=TA/174/02&start=2024&end=2024')).json();
  assert.equal(fine.totals[0].EXEC.status,'ok');
  assert.equal(fine.totals[0].EXEC.nominal_cents,69201772100);
  const old=await (await page.request.get('/api/explorer?topic=maprimerenov&start=2017&end=2019')).json();
  assert(old.totals.every(y=>y.EXEC.value===null&&y.EXEC.status==='not_applicable'));
  await page.locator('[data-view="credits"]').click();await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'03-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
  assert.deepEqual(errors,[]);
  await fs.writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,errors,exec2024CP:1072217721,ecology2024CP:parent.value,ecologyWithoutMPR2024CP:data.totals[0].EXEC.value,subtracted:692017721,checks:['filter','annual-series','cross-mission','source-page','PDF','inflation','saved-and-URL','reset','program-remainder','unaffected-program','subtraction-provenance','CSV-download','movements','missing-detail','pre-creation','mobile']},null,2));
  console.log('MaPrimeRénov’ browser checks passed.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
