from pathlib import Path
p=Path('oracle.py');s=p.read_text('utf-8')
s=s.replace('self.groups=[];raw=[]','self.documentary_nodes=set();self.groups=[];raw=[]')
s=s.replace('group_keys.add(key)','group_keys.add(key);self.documentary_nodes.add(key)')
s=s.replace('b,m,y,_,p=key;self.paths[(b,m)].add(p)','b,m,y,_,p=key;self.paths[(b,m)].add(p);self.documentary_nodes.add(key)')
s=s.replace('if key in self.leaves and any(',"if (key in self.leaves or key in getattr(self,'documentary_nodes',set())) and any(")
s=s.replace("unknown=set(cell.get('sources',[]))-set(ref.sources)","""if not params.get('exclude') and not params.get('topic') and hasattr(ref,'source_ids'):
                        required=ref.source_ids[(params['budget'],params['measure'],year,stage,path)]
                        absent=required-set(cell.get('sources',[]))
                        if absent:issue(key+' origine de la case',sorted(required),cell.get('sources',[]))
                    unknown=set(cell.get('sources',[]))-set(ref.sources)""")
p.write_text(s,'utf-8')
p=Path('audit.py');s=p.read_text('utf-8')
s=s.replace("code={p.name:digest(p) for p in HERE.glob('*.py')}","code={n:digest(HERE/n) for n in ('audit.py','oracle.py','management.py')}")
s=s.replace("env['NODE_PATH']=str(self.a.node.parent.parent/'node_modules')","env['NODE_PATH']=os.environ.get('AUDIT_NODE_MODULES',str(self.a.node.parent.parent/'node_modules'))")
s=s.replace("if (i+1)%20==0 or r.get('incomplete'):self.progress()","self.progress()")
p.write_text(s,'utf-8')
p=Path('service.py');s=p.read_text('utf-8')
s=s.replace("rid=s.get('run_id')","""if s.get('status')=='running' and process is not None and process.poll() is not None:
        s.update(status='interrupted',message='Le processus a été interrompu. Les contrôles enregistrés sont conservés.');write(STATE/'service-state.json',s)
    rid=s.get('run_id')""")
p.write_text(s,'utf-8')
p=Path('worker.py');s=p.read_text('utf-8').replace('import argparse,json,os,sys,time,traceback','import argparse,html,json,os,sys,time,traceback')
s=s.replace("save(out/'ECHEC.json',dict(error=str(e),traceback=traceback.format_exc()))","""(out/'rapport.html').write_text('<!doctype html><html lang="fr"><meta charset="utf-8"><title>Contrôle incomplet</title><h1>Contrôle incomplet</h1><p>'+html.escape(str(e))+'</p><p>Aucun certificat de conformité émis. Les points de reprise sont conservés.</p></html>','utf-8')
        save(out/'ECHEC.json',dict(error=str(e),traceback=traceback.format_exc()))""")
p.write_text(s,'utf-8')
p=Path('web/app.js');s=p.read_text('utf-8').replace("if(r){$('state')","if(r&&s.status==='complete'){$('state')")
s=s.replace("$('links').hidden=!s.report_url;","if(s.status!=='complete')document.querySelector('.status').removeAttribute('data-result');\n $('links').hidden=!s.report_url||s.status==='running';")
p.write_text(s,'utf-8')
