from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
QA=ROOT/'reports/avancement-audit-20260909/qa-word';QA.mkdir(parents=True,exist_ok=True)
contract=(ROOT/'reports/audit-20260909/qa-liens/artifact.md').read_text(encoding='utf-8')
(QA/'artifact.md').write_text(contract+'\nAdaptation : point d’avancement des lots 0 à 6 de l’audit. Même gabarit et parties préservées. Aucun changement de l’audit original.\n',encoding='utf-8')
builder=(ROOT/'tools/build_vectorisation_notice_docx.py').read_text(encoding='utf-8')
prefix=builder.split('records=[]')[0].replace("OUT = ROOT / 'reports/audit-20260909'", "OUT = ROOT / 'reports/avancement-audit-20260909'").replace("TARGET = ROOT / 'vectorisation-nos-deniers-20260909/_controle/Consignes pour la vectorisation.docx'", "TARGET = ROOT / 'reports/avancement-audit-20260909/Avancement de Nos Deniers après audit.docx'")
exec(prefix)
assert hashlib.sha256(REF.read_bytes()).hexdigest()=='d3006f9074e46823d103fe283be19901f55f75c19811558455d7a16c61797355'
records=[]
p=paragraph('Avancement de Nos Deniers',1);pr=p.find('w:pPr',NS);st=pr.find('w:pStyle',NS)
if st is None:st=E.SubElement(pr,w('pStyle'))
st.set(w('val'),'Title')
body.append(deepcopy(protos[2]))
paragraph('À : Jean-Christophe',3)
paragraph('De : chantier Nos Deniers',5)
paragraph('Date : 9 septembre 2026',6)
paragraph('Objet : avancement du développement et de la publication après audit',7)
body.append(deepcopy(protos[8]));body.append(deepcopy(protos[9]))
paragraph('Une première version utilisable en local',10,True)
paragraph('Les tableaux, comparaisons, exclusions, euros constants et exports fonctionnent sur les données intégrées. Le site reste généraliste. Mission Écologie et MaPrimeRénov’ servent de cas tests, avec les deux Excel de Marie comme référence des besoins. Le plan de l’audit n’est pas achevé : la finesse des données, les mouvements et la recherche restent les principaux travaux.')
paragraph('Le [site public](https://budget.lexmachine.net/) répond, mais sert encore la première version : 116 272 observations chiffrées et 769 références documentaires. La [version locale](http://127.0.0.1:8552/?start=2021&end=2024&scope=TA&measure=CP&budget=BG) contient 119 746 observations et 4 280 références. Ces compteurs désignent des enregistrements et des références, pas autant de rapports complets distincts. Vérification directe des deux API lors de ce point.')
paragraph('Où en sont les sept lots de l’audit',21,True)
paragraph('Lot 0 — Fiabilité visible : corrections locales réalisées. Tous les formats documentaires sont accessibles, le graphique décennal fonctionne sur mobile et les versions sont affichées. Les manques ne sont pas remplacés par zéro. Reste la remise à niveau du site public, avec sauvegarde et possibilité de retour à la version précédente.')
paragraph('Lot 1 — Tableau quotidien : bien avancé, incomplet. Consommé 2021–2022 et LFI 2026 ajoutés ; écarts, taux, variations annuelles et exports disponibles. Restent le PLF 2026, le détail récent par action et sous-action, les rapprochements encore ouverts et la vue complète par exercice selon les colonnes des Excel. LFI et consommé 2023–2025 sont intégrés surtout au programme.')
paragraph('Lot 2 — Périmètres et MaPrimeRénov’ : partiellement réalisé. Isoler ou retirer les parts identifiées du dispositif, exclure des programmes et corriger l’inflation fonctionne. Le choix Écologie hors MPR, P345 et P235 est disponible. Restent les années et étapes du dispositif non isolées, la précision des montants et les correspondances de nomenclature. Ces trois exclusions ne neutralisent pas tous les changements historiques.')
paragraph('Lot 3 — Vie des crédits : amorcé. Le registre des actes contient le seul décret d’annulation 2024-124. Les réserves couvrent le programme 174 de 2017 à 2025, avec les pages des neuf RAP. Restent les autres programmes, les autres actes, les mouvements bruts, les dates et les rapprochements des reports et FdC/AdP. Aucun historique national exhaustif des gels et dégels n’est encore fourni.')
paragraph('Lot 4 — Recherche documentaire : corpus préparé, raccordement au site à faire. La bibliothèque permet déjà de chercher les titres et ouvrir les documents. Dans le dernier point de la tâche « Eur-LEX », 510 documents sur 4 914 étaient extraits et 10 préindexés. Ce relevé est celui de cette tâche, pas un compteur en temps réel. La recherche dans les passages, la fédération des bases existantes et le raccordement applicatif de Tricoteuses restent à réaliser.')
paragraph('Lot 5 — Audit IA : à développer. L’export d’une sélection et de ses preuves prépare ce travail. Il manque le parcours qui produit une analyse de l’évolution, cite les passages pertinents et distingue les explications établies des hypothèses. Son contrôle dépend de la recherche du lot 4.')
paragraph('Lot 6 — Navette et collaboration : reporté conformément à la priorité fixée. L’étude des dépôts ouverts et les fonctions de suivi des amendements viendront après les tableaux et l’audit IA. Elles restent dans le plan général.')
paragraph('Ce qui vient ensuite',21,True)
paragraph('1. Compléter le cas Mission Écologie à partir des Excel : chaque année et chaque étape, puis le détail réellement documenté. Distinguer fonds prévus et rattachés, crédits ouverts, consommation, régularisations proposées et définitives. Une partie des réponses est déjà dans les RAP collectés ; il faut encore l’extraire et la contrôler.')
paragraph('2. Étendre MaPrimeRénov’ et les réserves aux autres programmes concernés. Vérifier les montants et leur périmètre avant addition ou retrait. Les postes sans données restent visibles et les calculs incomplets sont signalés.')
paragraph('3. Publier un lot local validé sur budget.lexmachine.net, sans attendre que toutes les missions soient complètes : préparer le paquet, sauvegarder la version publique, activer la mise à jour et contrôler HTTPS, API, tableaux, exports et téléchargements. Aucune nouvelle activation publique n’a été faite pendant ce point.')
paragraph('4. Raccorder l’index documentaire lorsqu’il est prêt, puis construire l’analyse IA depuis une sélection chiffrée et sourcée. La vectorisation aide à retrouver les explications ; elle ne remplace pas la validation des tableaux numériques.')
paragraph('Ce qui est déjà vérifié',21,True)
paragraph('Les 59 tests unitaires du dernier lot passent, ainsi que les parcours navigateur Écologie, MaPrimeRénov’ et réserves. Les montants et sources antérieurs ont été comparés avant et après les changements. Le cas Écologie 2024 avec exclusions se rapproche du total de départ. Cela valide ce périmètre de tests, sans certifier toutes les missions et tous les détails de 2017 à 2026.')
paragraph('Référence de suivi : [Audit Nos Deniers et plan de développement](C:/Users/Jean-Christophe/Desktop/Nos Deniers/Audit Nos Deniers et plan de développement.docx), lots 0 à 6 et critères de recette. Le présent mémo actualise l’avancement ; l’audit original, les Excel et les corpus confiés à la vectorisation sont inchangés.')
footer=builder[builder.index('body.append(sect)'):].replace("(OUT/'qa-liens/vectorisation-word-controle.json')", "(OUT/'qa-word/word-controle.json')").replace('NOS DENIERS — VECTORISATION','NOS DENIERS — AVANCEMENT').replace('Nos Deniers dossier de vectorisation','Avancement de Nos Deniers après audit')
exec(footer)
