"""A short Word development memo, using the retained Nos Deniers template."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
QA=ROOT/'reports/reserves-et-consignes-20260909/qa-word'
QA.mkdir(parents=True,exist_ok=True)
contract=(ROOT/'reports/audit-20260909/qa-liens/artifact.md').read_text(encoding='utf-8')
(QA/'artifact.md').write_text(contract+'\nAdaptation présente : mémo métier et développement, onglets pilotes et réserves P174. Même référence, mêmes parties préservées. Aucune consigne de modification du paquet de vectorisation.\n',encoding='utf-8')
builder=(ROOT/'tools/build_vectorisation_notice_docx.py').read_text(encoding='utf-8')
prefix=builder.split('records=[]')[0]
prefix=prefix.replace("OUT = ROOT / 'reports/audit-20260909'", "OUT = ROOT / 'reports/reserves-et-consignes-20260909'")
prefix=prefix.replace("TARGET = ROOT / 'vectorisation-nos-deniers-20260909/_controle/Consignes pour la vectorisation.docx'", "TARGET = ROOT / 'reports/reserves-et-consignes-20260909/Réserves et dossiers tests de Nos Deniers.docx'")
exec(prefix)
assert hashlib.sha256(REF.read_bytes()).hexdigest()=='d3006f9074e46823d103fe283be19901f55f75c19811558455d7a16c61797355'
records=[]
p=paragraph('Réserves et dossiers tests de Nos Deniers',1)
pr=p.find('w:pPr',NS);st=pr.find('w:pStyle',NS)
if st is None:st=E.SubElement(pr,w('pStyle'))
st.set(w('val'),'Title')
body.append(deepcopy(protos[2]))
paragraph('À : Jean-Christophe et Marie',3)
paragraph('De : chantier Nos Deniers',5)
paragraph('Date : 9 septembre 2026',6)
paragraph('Objet : appliquer les explications des Excel et les données des RAP',7)
body.append(deepcopy(protos[8]));body.append(deepcopy(protos[9]))
paragraph('Les premières réserves sont consultables',10,True)
paragraph('La version locale comporte deux accès directs, Mission Écologie et MaPrimeRénov’. Ils conservent les années, le choix AE ou CP et la correction de l’inflation. Chaque accès rétablit le périmètre du dossier et efface les exclusions précédentes. Les tableaux et exports existants restent accessibles.')
paragraph('[Ouvrir Nos Deniers en local](http://127.0.0.1:8552/?start=2017&end=2025&measure=CP&budget=BG&scope=TA). Pour voir les réserves, choisir « Mouvements et réserves ». Les nouveautés décrites ici ne sont pas encore déployées sur le site public.')
paragraph('La première série de réserves couvre le programme 174, Énergie, climat et après-mines, de 2017 à 2025. Elle distingue la réserve initiale, les surgels, les dégels, les annulations sur réserve lorsqu’une ligne est publiée et le solde avant le schéma de fin de gestion. Les montants sont consultables en AE ou CP, en euros courants ou constants, avec la page PDF et un export des preuves.')
paragraph('Dix-huit observations annuelles AE ou CP, issues de neuf RAP, passent 96 rapprochements de colonnes et de soldes. Les neuf pages de réserve ont été vérifiées visuellement. Les 51 tests unitaires de l’application passent, ainsi que les contrôles navigateur des dossiers et des réserves. Ce premier lot ne constitue ni un total de la mission ni une mesure de la réserve propre à MaPrimeRénov’.')
paragraph('Les RAP apportent bien des informations sur les gels',21,True)
paragraph('Le repérage retrouve des rubriques de réserve dans les neuf RAP Écologie de 2017 à 2025. L’affirmation selon laquelle il manquerait nécessairement les documents pour traiter les gels était trop large. Une partie importante du travail restant relève de l’extraction et de la qualification de documents déjà collectés.')
paragraph('Exemple vérifié : pour le programme 174 en 2024, le tableau indique 298 406 398 € de réserve initiale en CP, 1 403 516 085 € de surgels et −1 444 830 817 € de dégels. Le solde publié est 257 091 666 €, avant le schéma de fin de gestion. [Lire le RAP 2024 page 437](http://127.0.0.1:8552/api/download/SOURCE2024#page=437).')
paragraph('Le zéro doit être interprété à la date du tableau. En 2018, la ligne « Dégels » indique zéro, tandis que le texte décrit un dégel en fin d’exercice. En 2025, un autre programme explique que des crédits ont été dégelés puis annulés. Débloquer une réserve ne signifie donc pas toujours autoriser une nouvelle dépense. Le solde non consommé ne mesure pas le gel.')
paragraph('Ce que les explications des Excel changent',21,True)
paragraph('L’onglet « Explications tableau évolution » du classeur Mission écologie 2023 à 2025 fournit un guide de lecture par étape et niveau de détail. L’onglet « Consignes Marie » de l’autre classeur, omis du premier export, est désormais lu et conservé comme référence métier. Les deux originaux restent inchangés. Leurs explications ne sont pas importées automatiquement comme des faits budgétaires.')
paragraph('Les cellules C2, F2 et G2 du premier onglet imposent de distinguer les fonds de concours et attributions de produits prévus, les crédits effectivement rattachés et les crédits consommés. La cellule K2 correspond à un solde ouverts moins consommés, distinct de la réserve. Les cellules L2 à N2 orientent vers les régularisations et reports ; il faut vérifier les actes définitifs, et ne pas confondre proposition et loi promulguée.')
paragraph('La cellule A3 de « Consignes Marie » et la cellule E3 de l’autre onglet décrivent un périmètre de comparaison excluant MaPrimeRénov’, Service public de l’énergie et le programme nucléaire créé en 2025. Ce sera un périmètre choisi et documenté : ces seuls retraits ne prouvent pas que tous les changements de nomenclature ont été neutralisés.')
paragraph('Les cellules D2 à G2 de « Consignes Marie » demandent les variations annuelles, les euros constants de 2017 et l’évolution réelle depuis 2017. Le bouton inflation actuel assure la conversion des montants. Les indicateurs de variation et le périmètre combinant les trois exclusions restent à compléter et vérifier.')
paragraph('Les deux dossiers guideront les prochains contrôles',21,True)
paragraph('Mission Écologie : rapprocher chaque étape PLF, LFI et consommé des sources, puis les mouvements et les réserves. Étendre les réserves aux autres programmes et distinguer les dates de gestion des bilans annuels. La nomenclature annuelle, les données absentes et le niveau réellement publié doivent rester visibles.')
paragraph('MaPrimeRénov’ : suivre les financements entre missions et programmes, puis retirer uniquement les parts identifiées du reste de l’écologie. Le RAP 2023 page 439 confirme 2 027 954 906 € en AE et 1 216 572 951 € en CP pour la part décrite dans le programme 174. Cette précision est à rapprocher de la série actuelle, fondée en partie sur des montants arrondis, et des autres programmes avant toute substitution ou addition.')
paragraph('Le RAP 2024 page 437 décrit aussi des annulations concernant MaPrimeRénov’. Elles permettront d’enrichir le suivi du dispositif après rapprochement avec les actes et les crédits ouverts. La réserve globale du programme 174 ne sera pas affectée automatiquement à MaPrimeRénov’.')
paragraph('La vectorisation peut continuer',21,True)
paragraph('Les RAP exploités ici sont déjà dans le corpus transmis. Aucune reprise générale des embeddings n’est nécessaire. Le dossier en cours de vectorisation et son complément sont laissés intacts. Les exports des explications Excel restent dans le dossier de travail de ce mémo ; ils peuvent servir à concevoir et tester le service sans être ajoutés à l’index documentaire.')
reg=json.loads((ROOT/'budget_service/data/reserves-p174.json').read_text(encoding='utf-8'))
sid=next(r['source'] for r in reg['records'] if r['year']==2024)
for rel in rels:
 if 'SOURCE2024' in rel.get('Target',''):rel.set('Target',rel.get('Target').replace('SOURCE2024',sid))
for item in all_links:item['url']=item['url'].replace('SOURCE2024',sid)
footer=builder[builder.index('body.append(sect)'):]
footer=footer.replace("(OUT/'qa-liens/vectorisation-word-controle.json')","(OUT/'qa-word/word-controle.json')")
footer=footer.replace('NOS DENIERS — VECTORISATION','NOS DENIERS — DÉVELOPPEMENT')
footer=footer.replace('Nos Deniers dossier de vectorisation','Réserves et dossiers tests de Nos Deniers')
exec(footer)
