// UI verification only; use the site's existing visual design and controls.
const { chromium } = require('playwright');
const fs = require('fs');
const out = 'reports/integration-annexes-20260928';
(async () => {
  const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  page.setDefaultTimeout(60000);
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const query = 'start=2019&end=2019&budget=BG&measure=CP&scope=TA';
  await page.goto('http://127.0.0.1:8552/?'+query);
  await page.locator('.summary .metric').first().waitFor();
  await page.locator('[data-mode="series"]').click();
  await page.locator('#stage').selectOption('OUVERT');
  const amount = page.locator('button.amount[data-cell-scope="TA/159"][data-stage="OUVERT"]').first();
  await amount.waitFor(); await amount.click();
  await page.waitForFunction(() => document.querySelector('#source-content').innerText.includes('508'));
  const sourceText = (await page.locator('#source-content').innerText()).replace(/[\u00a0\u202f]/g, ' ');
  if (!sourceText.includes('508 222 323,58')) throw Error('Montant source P159 incorrect');
  const links = await page.locator('#source-content a[href*="/api/download/"]').evaluateAll(xs => xs.map(x => x.getAttribute('href')));
  if (!links.some(x=>x.includes('#page=35'))) throw Error('Page de la valeur P159 manquante');
  await page.screenshot({path:out+'/ui-source-p159.png'});
  await page.keyboard.press('Escape');
  const before = await (await page.request.get('http://127.0.0.1:8552/api/explorer?'+query)).json();
  const toggler = page.locator('[data-exclude="TA/159"]');
  await toggler.click();
  await page.waitForFunction(()=>new URL(location.href).searchParams.get('exclude')?.includes('TA/159'));
  const excluded = await (await page.request.get('http://127.0.0.1:8552/api/explorer?'+query+'&exclude=%5B%22TA%2F159%22%5D')).json();
  if (before.totals[0].OUVERT.nominal_cents-excluded.totals[0].OUVERT.nominal_cents!==50822232358) throw Error('Soustraction P159 incorrecte');
  await page.locator('[data-restore="TA/159"]').first().click();
  await page.waitForFunction(()=>new URL(location.href).searchParams.get('exclude')==='[]');
  await page.locator('[data-exclude="TA/159"]').waitFor();
  // Previously unresolved management cell: a real source discrepancy remains visible.
  await page.goto('http://127.0.0.1:8552/?start=2017&end=2017&budget=BG&measure=AE&scope=AA');
  await page.locator('.summary .metric').first().waitFor();
  await page.locator('[data-mode="series"]').click();
  await page.locator('#stage').selectOption('FDC');
  await page.locator('button.amount[data-cell-scope="AA/151"][data-stage="FDC"]').click();
  await page.waitForFunction(()=>document.querySelector('#source-content').innerText.includes('pas encore intégré'));
  const pending = await page.locator('#source-content').innerText();
  if (!pending.includes('cause doit être qualifiée')) throw Error('Avertissement absent');
  await page.screenshot({path:out+'/ui-pending.png'});
  await page.keyboard.press('Escape');
  // The added FdC series is available through the same stage selector.
  const fd = page.locator('button.amount[data-cell-scope="AA/105"][data-stage="FDC"]');
  if (await fd.locator('.proof-hint').count()) throw Error('FdC confirmé affiché manquant');
  await page.screenshot({path:out+'/ui-management.png'});
  await page.setViewportSize({width:390,height:844});
  const audit = page.getByRole('link',{name:'Contrôle indépendant des montants'});
  if (!await audit.isVisible()) throw Error('Bouton de contrôle mobile absent');
  await page.screenshot({path:out+'/ui-mobile.png'});
  const variant = await page.request.get('http://127.0.0.1:8556/api/bootstrap');
  const primary = await page.request.get('http://127.0.0.1:8552/api/bootstrap');
  if ((await variant.json()).meta.data_version !== (await primary.json()).meta.data_version) throw Error('Aperçus différents');
  if (errors.length) throw Error(errors.join('\n'));
  const report = {passed:true,source_page:true,exclusion_and_restore:true,pending_warning:true,management_stage:true,mobile_audit_link:true,visual_variant_same_data:true,errors};
  fs.writeFileSync(out+'/browser.json',JSON.stringify(report,null,2));
  console.log(JSON.stringify(report)); await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
